name: Testing talk-booking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
  pytest:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install deps
        run: |
          pip install -U pip
          pip install poetry==1.2.2
          cd services/talk_booking/
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Setup GIT
        run: |
          git config --global user.name "talk_booking"
          git config --global user.email "talk_booking@pytest.python"
      - name: Run tests
        run: poetry run python -m pytest --junitxml=report.xml --cov=./ --cov-report=xml tests/unit tests/integration
